/**
 * The drawer, under this design system's own name.
 */

export {
  Drawer,
  DrawerActionTrigger,
  type DrawerActionTriggerProps,
  DrawerBackdrop,
  type DrawerBackdropProps,
  DrawerBody,
  type DrawerBodyProps,
  DrawerCloseTrigger,
  type DrawerCloseTriggerProps,
  DrawerContent,
  type DrawerContentProps,
  DrawerContext,
  DrawerDescription,
  type DrawerDescriptionProps,
  type DrawerFocusOutsideEvent,
  DrawerFooter,
  type DrawerFooterProps,
  DrawerHeader,
  type DrawerHeaderProps,
  type DrawerInteractOutsideEvent,
  type DrawerOpenChangeDetails,
  type DrawerPointerDownOutsideEvent,
  DrawerPositioner,
  type DrawerPositionerProps,
  DrawerRoot,
  type DrawerRootProps,
  DrawerRootPropsProvider,
  DrawerRootProvider,
  type DrawerRootProviderProps,
  DrawerTitle,
  type DrawerTitleProps,
  DrawerTrigger,
  type DrawerTriggerProps,
  useDrawer,
  useDrawerContext,
  type UseDrawerProps,
  type UseDrawerReturn,
  useDrawerStyles,
} from "@chakra-ui/react/drawer";
