/**
 * The slider, under this design system's own name.
 */

export {
  Slider,
  SliderContext,
  SliderControl,
  type SliderControlProps,
  SliderDraggingIndicator,
  type SliderDraggingIndicatorProps,
  SliderHiddenInput,
  SliderLabel,
  type SliderLabelProps,
  SliderMarker,
  SliderMarkerGroup,
  type SliderMarkerGroupProps,
  SliderMarkerIndicator,
  type SliderMarkerIndicatorProps,
  SliderMarkerLabel,
  type SliderMarkerLabelProps,
  type SliderMarkerProps,
  SliderPropsProvider,
  SliderRange,
  type SliderRangeProps,
  SliderRoot,
  type SliderRootProps,
  SliderRootProvider,
  type SliderRootProviderProps,
  SliderThumb,
  type SliderThumbProps,
  SliderTrack,
  type SliderTrackProps,
  type SliderValueChangeDetails,
  SliderValueText,
  type SliderValueTextProps,
  useSlider,
  useSliderContext,
  type UseSliderProps,
  type UseSliderReturn,
  useSliderStyles,
} from "@chakra-ui/react/slider";
