/**
 * Draws pictures and sound, and the frames they sit in.
 *
 * Every component here is Chakra's under this design system's own name, so an application imports
 * the styling engine nowhere. That is the seam the theme's provider is: the engine underneath stays
 * this repository's to change.
 *
 * @packageDocumentation
 */

export {
  Avatar,
  AvatarContext,
  AvatarFallback,
  type AvatarFallbackProps,
  AvatarGroup,
  type AvatarGroupProps,
  AvatarIcon,
  type AvatarIconProps,
  AvatarImage,
  type AvatarImageProps,
  AvatarPropsProvider,
  AvatarRoot,
  type AvatarRootProps,
  AvatarRootProvider,
  type AvatarStatusChangeDetails,
  useAvatar,
  useAvatarContext,
  type UseAvatarProps,
  type UseAvatarReturn,
  useAvatarStyles,
} from "#avatar/avatar.ts";
export {
  Carousel,
  CarouselAutoplayIndicator,
  type CarouselAutoplayIndicatorProps,
  type CarouselAutoplayStatusDetails,
  CarouselAutoplayTrigger,
  type CarouselAutoplayTriggerProps,
  CarouselContext,
  CarouselControl,
  type CarouselControlProps,
  type CarouselDragStatusDetails,
  CarouselIndicator,
  CarouselIndicatorGroup,
  type CarouselIndicatorGroupProps,
  type CarouselIndicatorProps,
  CarouselIndicators,
  type CarouselIndicatorsProps,
  CarouselItem,
  CarouselItemGroup,
  type CarouselItemGroupProps,
  type CarouselItemProps,
  CarouselNextTrigger,
  type CarouselNextTriggerProps,
  type CarouselPageChangeDetails,
  CarouselPrevTrigger,
  type CarouselPrevTriggerProps,
  CarouselProgressText,
  type CarouselProgressTextProps,
  CarouselPropsProvider,
  CarouselRoot,
  type CarouselRootProps,
  CarouselRootProvider,
  type CarouselRootProviderProps,
  useCarousel,
  useCarouselContext,
  type UseCarouselProps,
  type UseCarouselReturn,
  useCarouselStyles,
} from "#carousel/carousel.ts";
export { createIcon, Icon, type IconProps, IconPropsProvider } from "#icon/icon.ts";
export {
  ImageCropperContext,
  type ImageCropperCropChangeDetails,
  type ImageCropperFlipChangeDetails,
  type ImageCropperFlipState,
  ImageCropperGrid,
  type ImageCropperGridProps,
  ImageCropperHandle,
  type ImageCropperHandlePosition,
  type ImageCropperHandleProps,
  imageCropperHandles,
  ImageCropperImage,
  type ImageCropperImageProps,
  ImageCropperPropsProvider,
  ImageCropperRoot,
  type ImageCropperRootBaseProps,
  type ImageCropperRootProps,
  ImageCropperRootProvider,
  type ImageCropperRootProviderProps,
  type ImageCropperRotationChangeDetails,
  ImageCropperSelection,
  type ImageCropperSelectionProps,
  ImageCropperViewport,
  type ImageCropperViewportProps,
  type ImageCropperZoomChangeDetails,
  useImageCropper,
  useImageCropperContext,
  type UseImageCropperContext,
  type UseImageCropperProps,
  type UseImageCropperReturn,
  useImageCropperStyles,
} from "#image-cropper/image-cropper.ts";
export { Image, type ImageProps } from "#image/image.ts";
export {
  QrCode,
  QrCodeFrame,
  type QrCodeFrameProps,
  QrCodeOverlay,
  type QrCodeOverlayProps,
  QrCodePattern,
  type QrCodePatternProps,
  QrCodePropsProvider,
  QrCodeRoot,
  type QrCodeRootProps,
  QrCodeRootProvider,
  useQrCode,
  useQrCodeContext,
  type UseQrCodeProps,
  type UseQrCodeReturn,
  useQrCodeStyles,
} from "#qr-code/qr-code.ts";
