/**
 * The dialog, under this design system's own name.
 */

export {
  Dialog,
  DialogActionTrigger,
  type DialogActionTriggerProps,
  DialogBackdrop,
  type DialogBackdropProps,
  DialogBody,
  type DialogBodyProps,
  DialogCloseTrigger,
  type DialogCloseTriggerProps,
  DialogContent,
  type DialogContentProps,
  DialogContext,
  DialogDescription,
  type DialogDescriptionProps,
  type DialogFocusOutsideEvent,
  DialogFooter,
  type DialogFooterProps,
  DialogHeader,
  type DialogHeaderProps,
  type DialogInteractOutsideEvent,
  type DialogOpenChangeDetails,
  type DialogPointerDownOutsideEvent,
  DialogPositioner,
  type DialogPositionerProps,
  DialogPropsProvider,
  DialogRoot,
  type DialogRootProps,
  DialogRootProvider,
  type DialogRootProviderProps,
  DialogTitle,
  type DialogTitleProps,
  DialogTrigger,
  type DialogTriggerProps,
  useDialog,
  useDialogContext,
  type UseDialogProps,
  type UseDialogReturn,
  useDialogStyles,
} from "@chakra-ui/react/dialog";
