/**
 * The steps, under this design system's own name.
 */

export {
  Steps,
  type StepsChangeDetails,
  StepsCompletedContent,
  type StepsCompletedContentProps,
  StepsContent,
  type StepsContentProps,
  StepsContext,
  StepsDescription,
  type StepsDescriptionProps,
  StepsIndicator,
  type StepsIndicatorProps,
  StepsItem,
  StepsItemContext,
  type StepsItemProps,
  StepsList,
  type StepsListProps,
  StepsNextTrigger,
  type StepsNextTriggerProps,
  StepsNumber,
  type StepsNumberProps,
  StepsPrevTrigger,
  type StepsPrevTriggerProps,
  StepsPropsProvider,
  StepsRoot,
  type StepsRootProps,
  StepsRootProvider,
  type StepsRootProviderProps,
  StepsSeparator,
  type StepsSeparatorProps,
  StepsStatus,
  type StepsStatusProps,
  StepsTitle,
  type StepsTitleProps,
  StepsTrigger,
  type StepsTriggerProps,
  useSteps,
  useStepsContext,
  useStepsItemContext,
  type UseStepsProps,
  type UseStepsReturn,
  useStepsStyles,
} from "@chakra-ui/react/steps";
