/**
 * The tags input, under this design system's own name.
 */

export {
  TagsInput,
  TagsInputClearTrigger,
  type TagsInputClearTriggerProps,
  TagsInputContext,
  TagsInputControl,
  type TagsInputControlProps,
  TagsInputHiddenInput,
  TagsInputInput,
  type TagsInputInputProps,
  TagsInputItem,
  TagsInputItemContext,
  TagsInputItemDeleteTrigger,
  type TagsInputItemDeleteTriggerProps,
  type TagsInputItemProps,
  TagsInputItems,
  type TagsInputItemsProps,
  TagsInputItemText,
  type TagsInputItemTextProps,
  TagsInputLabel,
  type TagsInputLabelProps,
  TagsInputPropsProvider,
  TagsInputRoot,
  type TagsInputRootProps,
  TagsInputRootProvider,
  type TagsInputRootProviderProps,
  type TagsInputValidityChangeDetails,
  type TagsInputValueChangeDetails,
  useTagsInput,
  type UseTagsInputContext,
  useTagsInputContext,
  type UseTagsInputItemContext,
  useTagsInputItemContext,
  type UseTagsInputProps,
  type UseTagsInputReturn,
  useTagsInputStyles,
} from "@chakra-ui/react/tags-input";
