/**
 * The popover, under this design system's own name.
 */

export {
  Popover,
  PopoverAnchor,
  type PopoverAnchorProps,
  PopoverArrow,
  type PopoverArrowProps,
  PopoverArrowTip,
  type PopoverArrowTipProps,
  PopoverBody,
  type PopoverBodyProps,
  PopoverCloseTrigger,
  type PopoverCloseTriggerProps,
  PopoverContent,
  type PopoverContentProps,
  PopoverContext,
  PopoverDescription,
  type PopoverDescriptionProps,
  type PopoverFocusOutsideEvent,
  PopoverFooter,
  type PopoverFooterProps,
  PopoverHeader,
  type PopoverHeaderProps,
  type PopoverInteractOutsideEvent,
  type PopoverOpenChangeDetails,
  type PopoverPointerDownOutsideEvent,
  PopoverPositioner,
  type PopoverPositionerProps,
  PopoverPropsProvider,
  PopoverRoot,
  type PopoverRootProps,
  PopoverRootProvider,
  type PopoverRootProviderProps,
  PopoverTitle,
  type PopoverTitleProps,
  PopoverTrigger,
  type PopoverTriggerProps,
  usePopover,
  usePopoverContext,
  type UsePopoverProps,
  type UsePopoverReturn,
  usePopoverStyles,
} from "@chakra-ui/react/popover";
