/**
 * The file upload, under this design system's own name.
 */

export {
  FileUpload,
  FileUploadClearTrigger,
  type FileUploadClearTriggerProps,
  FileUploadContext,
  FileUploadDropzone,
  FileUploadDropzoneContent,
  type FileUploadDropzoneContentProps,
  type FileUploadDropzoneProps,
  type FileUploadFileAcceptDetails,
  type FileUploadFileChangeDetails,
  type FileUploadFileError,
  type FileUploadFileMimeType,
  type FileUploadFileRejectDetails,
  type FileUploadFileRejection,
  FileUploadFileText,
  type FileUploadFileTextProps,
  FileUploadHiddenInput,
  FileUploadItem,
  FileUploadItemContent,
  type FileUploadItemContentProps,
  FileUploadItemDeleteTrigger,
  type FileUploadItemDeleteTriggerProps,
  FileUploadItemGroup,
  type FileUploadItemGroupProps,
  FileUploadItemName,
  type FileUploadItemNameProps,
  FileUploadItemPreview,
  FileUploadItemPreviewImage,
  type FileUploadItemPreviewImageProps,
  type FileUploadItemPreviewProps,
  type FileUploadItemProps,
  FileUploadItems,
  FileUploadItemSizeText,
  type FileUploadItemSizeTextProps,
  type FileUploadItemsProps,
  FileUploadLabel,
  type FileUploadLabelProps,
  FileUploadList,
  type FileUploadListProps,
  FileUploadPropsProvider,
  FileUploadRoot,
  type FileUploadRootProps,
  FileUploadRootProvider,
  type FileUploadRootProviderProps,
  FileUploadTrigger,
  type FileUploadTriggerProps,
  useFileUpload,
  useFileUploadContext,
  type UseFileUploadProps,
  type UseFileUploadReturn,
  useFileUploadStyles,
} from "@chakra-ui/react/file-upload";
