/**
 * The carousel, under this design system's own name.
 */

export {
  Carousel,
  CarouselAutoplayIndicator,
  type CarouselAutoplayIndicatorProps,
  type CarouselAutoplayStatusDetails,
  CarouselAutoplayTrigger,
  type CarouselAutoplayTriggerProps,
  CarouselContext,
  CarouselControl,
  type CarouselControlProps,
  type CarouselDragStatusDetails,
  CarouselIndicator,
  CarouselIndicatorGroup,
  type CarouselIndicatorGroupProps,
  type CarouselIndicatorProps,
  CarouselIndicators,
  type CarouselIndicatorsProps,
  CarouselItem,
  CarouselItemGroup,
  type CarouselItemGroupProps,
  type CarouselItemProps,
  CarouselNextTrigger,
  type CarouselNextTriggerProps,
  type CarouselPageChangeDetails,
  CarouselPrevTrigger,
  type CarouselPrevTriggerProps,
  CarouselProgressText,
  type CarouselProgressTextProps,
  CarouselPropsProvider,
  CarouselRoot,
  type CarouselRootProps,
  CarouselRootProvider,
  type CarouselRootProviderProps,
  useCarousel,
  useCarouselContext,
  type UseCarouselProps,
  type UseCarouselReturn,
  useCarouselStyles,
} from "@chakra-ui/react/carousel";
