/**
 * Arranges what is already there: the boxes, the stacks, the rules between them and the surfaces
 * they sit on.
 *
 * Every component here is Chakra's under this design system's own name, so an application imports
 * the styling engine nowhere. That is the seam the theme's provider is: the engine underneath stays
 * this repository's to change.
 *
 * @packageDocumentation
 */

export { AbsoluteCenter, type AbsoluteCenterProps } from "#absolute-center/absolute-center.ts";
export {
  Accordion,
  AccordionContext,
  type AccordionFocusChangeDetails,
  AccordionItem,
  AccordionItemBody,
  type AccordionItemBodyProps,
  AccordionItemContent,
  type AccordionItemContentProps,
  AccordionItemContext,
  AccordionItemIndicator,
  type AccordionItemIndicatorProps,
  type AccordionItemProps,
  AccordionItemTrigger,
  type AccordionItemTriggerProps,
  AccordionPropsProvider,
  AccordionRoot,
  type AccordionRootProps,
  AccordionRootProvider,
  type AccordionRootProviderProps,
  type AccordionValueChangeDetails,
  useAccordion,
  useAccordionContext,
  useAccordionItemContext,
  type UseAccordionProps,
  type UseAccordionReturn,
  useAccordionStyles,
} from "#accordion/accordion.ts";
export { AspectRatio, type AspectRatioProps } from "#aspect-ratio/aspect-ratio.ts";
export { Bleed, type BleedProps } from "#bleed/bleed.ts";
export { Box, type BoxProps } from "#box/box.ts";
export {
  Card,
  CardBody,
  type CardBodyProps,
  CardDescription,
  type CardDescriptionProps,
  CardFooter,
  type CardFooterProps,
  CardHeader,
  type CardHeaderProps,
  CardPropsProvider,
  CardRoot,
  type CardRootProps,
  CardTitle,
  type CardTitleProps,
  useCardStyles,
} from "#card/card.ts";
export { Center, type CenterProps } from "#center/center.ts";
export { Circle, type CircleProps } from "#circle/circle.ts";
export {
  Collapsible,
  CollapsibleContent,
  type CollapsibleContentProps,
  CollapsibleContext,
  CollapsibleIndicator,
  type CollapsibleIndicatorProps,
  type CollapsibleOpenChangeDetails,
  CollapsiblePropsProvider,
  CollapsibleRoot,
  type CollapsibleRootProps,
  CollapsibleRootProvider,
  type CollapsibleRootProviderProps,
  CollapsibleTrigger,
  type CollapsibleTriggerProps,
  useCollapsible,
  useCollapsibleContext,
  type UseCollapsibleProps,
  type UseCollapsibleReturn,
  useCollapsibleStyles,
} from "#collapsible/collapsible.ts";
export { Container, type ContainerProps, ContainerPropsProvider } from "#container/container.ts";
export { Flex, type FlexProps } from "#flex/flex.ts";
export { Float, type FloatProps } from "#float/float.ts";
export { Frame, type FrameProps, FramePropsProvider } from "#frame/frame.ts";
export { Grid, GridItem, type GridItemProps, type GridProps } from "#grid/grid.ts";
export { Group, type GroupProps } from "#group/group.ts";
export {
  JsonTreeViewPropsProvider,
  JsonTreeViewRoot,
  type JsonTreeViewRootProps,
  JsonTreeViewRootProvider,
  type JsonTreeViewRootProviderProps,
  JsonTreeViewTree,
  type JsonTreeViewTreeProps,
  useJsonTreeView,
  type UseJsonTreeViewProps,
  type UseJsonTreeViewReturn,
  useJsonTreeViewStyles,
} from "#json-tree-view/json-tree-view.ts";
export { Presence, type PresenceProps } from "#presence/presence.ts";
export {
  ScrollArea,
  ScrollAreaContent,
  type ScrollAreaContentProps,
  ScrollAreaContext,
  ScrollAreaCorner,
  type ScrollAreaCornerProps,
  ScrollAreaPropsProvider,
  ScrollAreaRoot,
  type ScrollAreaRootProps,
  ScrollAreaRootProvider,
  type ScrollAreaRootProviderProps,
  ScrollAreaScrollbar,
  type ScrollAreaScrollbarProps,
  ScrollAreaThumb,
  type ScrollAreaThumbProps,
  ScrollAreaViewport,
  type ScrollAreaViewportProps,
  useScrollArea,
  useScrollAreaContext,
  type UseScrollAreaProps,
  type UseScrollAreaReturn,
  useScrollAreaStyles,
} from "#scroll-area/scroll-area.ts";
export { Separator, type SeparatorProps, SeparatorPropsProvider } from "#separator/separator.ts";
export { Show, type ShowProps } from "#show/show.ts";
export { SimpleGrid, type SimpleGridProps } from "#simple-grid/simple-grid.ts";
export { Spacer, type SpacerProps } from "#spacer/spacer.ts";
export {
  createSplitterRegistry,
  getSplitterLayout,
  Splitter,
  SplitterContext,
  type SplitterExpandCollapseDetails,
  SplitterPanel,
  type SplitterPanelData,
  type SplitterPanelProps,
  SplitterPropsProvider,
  type SplitterRegistryProps,
  type SplitterRegistryReturn,
  type SplitterResizeDetails,
  type SplitterResizeEndDetails,
  SplitterResizeTrigger,
  SplitterResizeTriggerIndicator,
  type SplitterResizeTriggerIndicatorProps,
  type SplitterResizeTriggerProps,
  SplitterResizeTriggerSeparator,
  type SplitterResizeTriggerSeparatorProps,
  SplitterRoot,
  type SplitterRootBaseProps,
  type SplitterRootProps,
  SplitterRootProvider,
  type SplitterRootProviderBaseProps,
  type SplitterRootProviderProps,
  useSplitter,
  useSplitterContext,
  type UseSplitterContext,
  type UseSplitterProps,
  type UseSplitterReturn,
  useSplitterStyles,
} from "#splitter/splitter.ts";
export { Square, type SquareProps } from "#square/square.ts";
export {
  HStack,
  Stack,
  type StackProps,
  StackSeparator,
  type StackSeparatorProps,
  VStack,
} from "#stack/stack.ts";
export { Sticky, type StickyProps } from "#sticky/sticky.ts";
export {
  SwapIndicator,
  type SwapIndicatorProps,
  SwapPropsProvider,
  SwapRoot,
  type SwapRootProps,
  SwapRootProvider,
  type SwapRootProviderProps,
  useSwap,
  useSwapContext,
  type UseSwapProps,
  type UseSwapReturn,
  useSwapStyles,
} from "#swap/swap.ts";
export {
  Timeline,
  TimelineConnector,
  type TimelineConnectorProps,
  TimelineContent,
  type TimelineContentProps,
  TimelineDescription,
  type TimelineDescriptionProps,
  TimelineIndicator,
  type TimelineIndicatorProps,
  TimelineItem,
  type TimelineItemProps,
  TimelineRoot,
  type TimelineRootProps,
  TimelineRootPropsProvider,
  TimelineSeparator,
  type TimelineSeparatorProps,
  TimelineTitle,
  type TimelineTitleProps,
  useTimelineStyles,
} from "#timeline/timeline.ts";
export {
  TreeView,
  TreeViewBranch,
  TreeViewBranchContent,
  type TreeViewBranchContentProps,
  TreeViewBranchControl,
  type TreeViewBranchControlProps,
  TreeViewBranchIndentGuide,
  type TreeViewBranchIndentGuideProps,
  TreeViewBranchIndicator,
  type TreeViewBranchIndicatorProps,
  type TreeViewBranchProps,
  TreeViewBranchText,
  type TreeViewBranchTextProps,
  TreeViewBranchTrigger,
  type TreeViewBranchTriggerProps,
  TreeViewContext,
  type TreeViewExpandedChangeDetails,
  type TreeViewFocusChangeDetails,
  TreeViewItem,
  TreeViewItemIndicator,
  type TreeViewItemIndicatorProps,
  type TreeViewItemProps,
  TreeViewItemText,
  type TreeViewItemTextProps,
  TreeViewLabel,
  type TreeViewLabelProps,
  type TreeViewLoadChildrenCompleteDetails,
  type TreeViewLoadChildrenDetails,
  TreeViewNode,
  TreeViewNodeCheckbox,
  TreeViewNodeCheckboxIndicator,
  type TreeViewNodeCheckboxIndicatorProps,
  type TreeViewNodeCheckboxProps,
  TreeViewNodeContext,
  type TreeViewNodeProps,
  TreeViewNodeProvider,
  type TreeViewNodeProviderProps,
  type TreeViewNodeRenderProps,
  type TreeViewNodeState,
  TreeViewRoot,
  type TreeViewRootProps,
  TreeViewRootProvider,
  type TreeViewRootProviderProps,
  type TreeViewSelectionChangeDetails,
  TreeViewTree,
  type TreeViewTreeProps,
  useTreeView,
  useTreeViewContext,
  useTreeViewNodeContext,
  type UseTreeViewProps,
  type UseTreeViewReturn,
  useTreeViewStyles,
} from "#tree-view/tree-view.ts";
export { VisuallyHidden, visuallyHiddenStyle } from "#visually-hidden/visually-hidden.ts";
export { Wrap, WrapItem, type WrapItemProps, type WrapProps } from "#wrap/wrap.ts";
