/**
 * The floating panel, under this design system's own name.
 */

export {
  FloatingPanel,
  FloatingPanelBody,
  type FloatingPanelBodyProps,
  FloatingPanelCloseTrigger,
  type FloatingPanelCloseTriggerProps,
  FloatingPanelContent,
  type FloatingPanelContentProps,
  FloatingPanelContext,
  FloatingPanelControl,
  type FloatingPanelControlProps,
  FloatingPanelDragTrigger,
  type FloatingPanelDragTriggerProps,
  FloatingPanelHeader,
  type FloatingPanelHeaderProps,
  type FloatingPanelOpenChangeDetails,
  type FloatingPanelPositionChangeDetails,
  FloatingPanelPositioner,
  type FloatingPanelPositionerProps,
  FloatingPanelPropsProvider,
  FloatingPanelResizeTrigger,
  type FloatingPanelResizeTriggerProps,
  FloatingPanelResizeTriggers,
  FloatingPanelRoot,
  type FloatingPanelRootBaseProps,
  type FloatingPanelRootProps,
  FloatingPanelRootProvider,
  type FloatingPanelRootProviderBaseProps,
  type FloatingPanelRootProviderProps,
  type FloatingPanelSizeChangeDetails,
  type FloatingPanelStageChangeDetails,
  FloatingPanelStageTrigger,
  type FloatingPanelStageTriggerProps,
  FloatingPanelTitle,
  type FloatingPanelTitleProps,
  FloatingPanelTrigger,
  type FloatingPanelTriggerProps,
  useFloatingPanel,
  useFloatingPanelContext,
  type UseFloatingPanelProps,
  type UseFloatingPanelReturn,
  useFloatingPanelStyles,
} from "@chakra-ui/react/floating-panel";
