/**
 * The code block, under this design system's own name.
 */

export {
  CodeBlock,
  type CodeBlockAdapter,
  CodeBlockAdapterProvider,
  CodeBlockCode,
  type CodeBlockCodeProps,
  CodeBlockCodeText,
  type CodeBlockCodeTextProps,
  CodeBlockCollapseIndicator,
  type CodeBlockCollapseIndicatorProps,
  CodeBlockCollapseText,
  type CodeBlockCollapseTextProps,
  CodeBlockCollapseTrigger,
  type CodeBlockCollapseTriggerProps,
  CodeBlockContent,
  type CodeBlockContentProps,
  CodeBlockContext,
  type CodeBlockContextProps,
  CodeBlockControl,
  type CodeBlockControlProps,
  CodeBlockCopyIndicator,
  type CodeBlockCopyIndicatorProps,
  CodeBlockCopyTrigger,
  type CodeBlockCopyTriggerProps,
  CodeBlockFooter,
  type CodeBlockFooterProps,
  CodeBlockHeader,
  type CodeBlockHeaderProps,
  CodeBlockOverlay,
  type CodeBlockOverlayProps,
  CodeBlockRoot,
  type CodeBlockRootProps,
  CodeBlockTitle,
  type CodeBlockTitleProps,
  createHighlightJsAdapter,
  createShikiAdapter,
  type HighlightJsAdapterOptions,
  plainTextAdapter,
  type ShikiAdapterOptions,
} from "@chakra-ui/react/code-block";
