/**
 * The editable, under this design system's own name.
 */

export {
  Editable,
  EditableArea,
  type EditableAreaProps,
  EditableCancelTrigger,
  type EditableCancelTriggerProps,
  EditableContext,
  EditableControl,
  type EditableControlProps,
  type EditableEditChangeDetails,
  EditableEditTrigger,
  type EditableEditTriggerProps,
  type EditableFocusOutsideEvent,
  EditableInput,
  type EditableInputProps,
  type EditableInteractOutsideEvent,
  type EditablePointerDownOutsideEvent,
  EditablePreview,
  type EditablePreviewProps,
  EditablePropsProvider,
  EditableRoot,
  type EditableRootProps,
  EditableRootProvider,
  type EditableRootProviderProps,
  EditableSubmitTrigger,
  type EditableSubmitTriggerProps,
  EditableTextarea,
  type EditableTextareaProps,
  type EditableValueChangeDetails,
  useEditable,
  useEditableContext,
  type UseEditableProps,
  type UseEditableReturn,
  useEditableStyles,
} from "@chakra-ui/react/editable";
